apiVersion: v1
kind: Service
metadata:
  name: servicio-frontend
spec:
  type: NodePort
  selector:
    app: deployment-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
